### PR TITLE
Add support for semantic versioning (Ref 007)

### LINKED ISSUE #114: 007-Support semantic versioning

### PR DESCRIPTION
**Pull request by sosna**
See details on the [issue thread](https://github.com/sdmx-twg/sdmx-rest/issues/114#issuecomment-688279665).

Close #114

### CODE REVIEW

**Comment by dosse** [comment]
@sosna Very good. I just have a few remarks:

(1) It seems that the possibility of no versioning (non-semantic versioning) is not yet fully served and not made sufficiently "justice".
E.g.:  
- For structure queries, it says: "_If no version is specified, the latest stable version should be returned._" Shouldn't we give more "easiness" to these use cases? I guess the best option would be to use "**~**" as default thus: "If no version is specified, the latest, whether stable or draft, version or non-versioned artefact should be returned."
- For data queries, the defaults should be: "*,FLOW_ID,~" and "AGENCY_ID,FLOW_ID,~" which allows using the query syntax also for non-versioned artefacts.
 - For schema queries, an additionally permitted version keyword should be "~", and it should be the default. 

PS. For more clarity, the definition "`~` | version | Returns the latest, possibly _draft_ version of a resource" could reformulated to "`~` | version | Returns the latest, whether _stable_ or _draft_, version of a resource or non-versioned resource"

(2) The concatenation of agencyIDs and resourceID should be changed from "+" to "," since it represent "OR", right ? 
E.g.:  
- In structure queries "_It is possible to set more than one agency, using `+` as separator (e.g. BIS+ECB)._" should be "It is possible to set more than one agency, using `,` as separator (e.g. BIS,ECB)." Similar for resourceID.  

(3) There are "all" keywords left in data queries, lines 20,30,31,35,36, and in "other queries", lines 28,29,30,34,35,36,47,

--> (2) & (3) Or do you intend making these changes within another feature implementation?

**Comment by sosna** [comment]
Thanks @dosse!

I have corrected (1) a and (1) c as you proposed.

(1) b has been taken care of in another [pull request](https://github.com/sdmx-twg/sdmx-rest/pull/124) (about improving data queries).

For (2) and (3), it is as you guessed, i.e. I will take care of the harmonization of operators / keywords in another PR, as it's not strictly speaking related to semver. I hope to be able to work on that next week.

**Comment by dosse** [comment]
Thanks @sosna.

Could I still suggest these additional changes please:
- structure queries, line 43: "_- If no parameters are specified, the **latest, whether stable, draft or non-versioned,** version of **all** resources, maintained by **any** maintenance agency should be returned._"  
- data queries, line 18: "*,FLOW_ID,\~" and "AGENCY_ID,FLOW_ID,\~"
- other queries, line 15: "*,FLOW_ID,\~" and "AGENCY_ID,FLOW_ID,\~"
- sdmx-rest.yaml, line 255: "_The keyword `~` can be used to return the latest, whether stable, draft or non-versioned, version of the matching resource._", line 294: "_The keyword `*` can be used to return all, whether stable, draft or non-versioned, versions of the matching resource._", line 296: "The keyword `~` can be used to return the latest, whether stable, draft or non-versioned, version of the matching resource."

**Comment by sosna** [comment]
Thanks, @dosse!

I took care of pt. 1 and 4. I just changed the order a bit, to avoid the "non-versioned, version" sequence, but the meaning should be the same.

Re. pt. 2: It's already taken care of this in the [PR for data queries](https://github.com/sdmx-twg/sdmx-rest/blob/cr-117-1/v2_1/ws/rest/docs/4_4_data_queries.md).

Re. pt. 3: I will also do the changes in the PR for data queries as I see availability queries and data queries as belonging together. At the difference with pt. 2, I have not worked on these yet, but I hope to be able to do that next week.

Thanks.

**Review by dosse — APPROVED** [review]
Great, thanks.

**Pull request merged**
