### PR TITLE
Add VTL resources

### LINKED ISSUE #73: Add VTL resources
VTL defines a few additional MaintainableArtefacts (e.g. TransformationScheme, RulesetScheme, etc.). They should be added as new resource types to the documentation and the OpenAPI definition.

### PR DESCRIPTION
**Pull request by sosna**
Fix #73 

Some questions to the VTL group are still pending but this version takes care of what has been sent to us so far (i.e. the list of new maintainable artefacts).

### CODE REVIEW

**Comment by stratosn** [comment]
One comment and one question:
- In the referencing tables, Dataflow needs to be added in the NameAliasScheme as children (and consequently NameAliasScheme as parent to the Dataflow).
- All new VTL artefacts are supposed to follow the ItemScheme pattern. Should we also add them, as Item Schemes, in the Item queries?

**Comment by sosna** [comment]
Thanks, Stratos.

I have taken care of the comment (cf. commit [0b11273](https://github.com/sdmx-twg/sdmx-rest/pull/76/commits/0b11273fd4f8b13731a2c4f1c7890e3923592773)). 

Regarding your question: I think it is covered by commit [f17b6cc](https://github.com/sdmx-twg/sdmx-rest/pull/76/commits/f17b6cc21eb81134a0d6bbe22f3aa289a3792cec), referenced just above your comment?

Also, I have added another commit, which adds the VTL artefacts to the list of allowed values for the `references` parameter (cf. commit [c67d8a3](https://github.com/sdmx-twg/sdmx-rest/pull/76/commits/c67d8a3edecc20810d0f43debbf8c70a5794169c)). I had completely overlooked that :(.

**Comment by stratosn** [comment]
Thanks Xavier, 
I think you also need to add the NameAliasScheme in the Dataflow parent references.

On the items (sorry for not making this clear) I was referring to the documentation, where the list of Item Schemes are described (https://github.com/sdmx-twg/sdmx-rest/blob/0b11273fd4f8b13731a2c4f1c7890e3923592773/v2_1/ws/rest/docs/4_3_structural_queries.md#additional-parameter-used-for-identifying-a-resource-for-item-scheme-types). Hence I did not check the yams file.

Finally, it might be that Dataflows could be referenced within Transformations, but since Dataflow references would be part of the VTL expression, I have some doubts (and will discuss them with the VTL group).

**Comment by sosna** [comment]
Thanks, @stratosn, I have made the 2 first changes you mentioned. Re. the 3rd one, let me know what is required once you have discussed the topic.

**Pull request closed without merging**
