### PR TITLE
Implementation of CR-39

### LINKED ISSUE #39: Retrieve several Items from ItemScheme (not only one)
Proposed changes (in **bold**):

Additional parameter used for identifying a resource, for item scheme types:
SDMX uses the item scheme pattern to model SDMX collections of items. These are:
categoryscheme
conceptscheme
codelist
organisationscheme
agencyscheme
dataproviderscheme
dataconsumerscheme
organisationunitscheme
reportingtaxonomy
For these collections, it is possible to use a 4th parameter for identifying **resources**. The rules for the 3 other parameters, as defined in the section above, remain valid.

Parameter	Type	Description
**itemList**	**A concatenation of strings** compliant with the SDMX common:NestedNCNameIDType for conceptscheme and agencyscheme, or with the SDMX common:NestedIDType in all other cases. **The OR operator is supported using the + character. For example, the following string can be used to retrieve the codes for Germany, United States and Japan from REF_AREA codelist: DE+US.JP.**	The id**s** of the item**s** to be returned.
This 4th parameter is used as follows:

protocol://ws-entry-point/resource/agencyID/resourceID/version/itemID**+itemID**

### PR DESCRIPTION
**Pull request by sosna**
@sdmx-twg/sdmx-rest-team CR-39 is ready for review.

Fix #39

### CODE REVIEW

**Comment by sosna** [comment]
Regular expressions have been tested with [Regex 101](https://regex101.com/) but it would be nice if you could pay particular attention to the changes there.

**Comment by Tzaphkiel** [comment]
- why did you not re-define a type and just put regex directly?
- if using a single regex, why (e.g.: `NestedNCNameIDType`) did you keep the  `xs:union memberTypes` and not used instead a `xs:pattern value=` ?
- It seems like your VersionType can allow for a `1.2.3.4` version...
perhaps this would work better: `all|latest|([0-9]+(\.[0-9]*){0,1})([+][0-9]+(\.[0-9]*){0,1})*`
- is this a valid triplet ID for `NestedNCNameIDType`: `-.@+_-+$_.-_`, i.e.: `-.@` & `_-` & `$_.-_` ??

**Comment by sosna** [comment]
@Tzaphkiel Points 1 and 2 have been modified as suggested. Points 3 and 4 are already implemented as per the SDMX 2.1 spec.

**Comment by agent96** [comment]
I was double checking the RegEx, any in XMLSPY it complains on the use of comma, 

> Value '([A-Za-z][A-Za-z0-9_\-]*(\.[A-Za-z][A-Za-z0-9_\-]*)*\,)?([A-Za-z0-9_@$\-]+)' is not a valid XML regular expression.

If I change *)*\,)? with a single \, to use a double backslash  \\, then it is okay, this occurs a few times, is this just a XMLSpy issue, or an error in the expression with escaping?

**Comment by sosna** [comment]
@agent96 The only place where I see this happening is in the regex for ProviderRefType. This is the one you meant, right?

If so, I checked and it's not one of the types that have been modified with the pull request. 

I checked the regex and it looks OK to me (i.e. a single \ is enough to escape characters (not like in Java regex where you need to use \\). I also tried the regex using [regex101](https://regex101.com/) and it looks OK to me.

In your error message, it looks like the \ characters are gone though (compare it with the definition in SDMXRestTypes.xsd).

**Comment by agent96** [comment]
Yes ProviderRefType and the same error twice in FlowRefType.  It's in XML Spy when it tries to validate the .xsd, it highlights the comma in red.  

invalid-escape: The given character escape is not recognized.
dt-pattern: Value '([A-Za-z0-9_@$\-]+)|(([A-Za-z][A-Za-z0-9_\-]*(\.[A-Za-z][A-Za-z0-9_\-]*)*)(\,[A-Za-z0-9_@$\-]+)(\,(l...' is not a valid XML regular expression.

I don't know if this is a false error or not.

**Comment by sosna** [comment]
Could you please replace ProviderRefType with the following and let me know if it works better?

([A-Za-z][A-Za-z0-9_\-]*(\.[A-Za-z][A-Za-z0-9_\-]*)*[,])?([A-Za-z0-9_@$\-]+)

The only difference is that instead of escaping the comma (\,), it is now defined as [,].

**Comment by agent96** [comment]
yes, it's happy with that. Thanks.

**Comment by sosna** [comment]
Thanks, Matt. I have updated the xsd file and tested the regex again and it looks ok.

**Pull request merged**
