### PR TITLE
Ref 013 - Reorganizing constraints

### LINKED ISSUE #120: 013-Reorganizing constraints
TBD

### PR DESCRIPTION
**Pull request by sosna**
Implements [Ref 013](https://github.com/sdmx-twg/sdmx-rest/issues/120).

In addition, missing VTL artefacts have been added to _artefactType_.

Close #120

### CODE REVIEW

**Comment by dosse** [comment]
@sosna 

1) My first comment would be about v2_1/ws/rest/docs/4_3_structural_queries.md which still allows for `contentconstraint`. I believe this is a mistake.

2) My second comment would be about the `availableconstraint` query used to return both previously called `actualconstraint` information and `availableconstraint` information, but if that's the case, shouldn't we rename the path segment to generically `availability` instead of `availableconstraint`? I see a confusion because neither  `actualconstraint` nor `availableconstraint` really still exist as structural artefacts, right? Or what type of response/message format do we get with the `availableconstraint` query? I'm sorry, if I missed things that I should know.

**Comment by agent96** [comment]
Re. pt. 2: that's fine with me

**Comment by stratosn** [comment]
As regards the resources, the question is how many messages we ultimately need. On the data side, we need the DataConstraint with the flag {{type="allowed|actual}}. On the metadata side, we do not need the flag, as there is no provision for allowed vs. actual MetadataConstraints.
Following that, the simplest would be to have: /dataconstraint,  /metadataconstraint, /availability
If deemed useful the first two could be grouped under /contentconstraint (I am not in favour, but it's only me).

**Comment by agent96** [comment]
Re. pt. 1: following Stratos' comment - it could be kept as an umbrella term for both types of constraint, I am also not sure if this is really useful at all.  So I would also be in favour of simplification unless we see a real use case that this grouping satisfies.

**Comment by sosna** [comment]
Thanks to all!

I have now updated the PR accordingly (i.e. renamed availability query and removed content constraint).

Could you please review? Thanks!

**Review by dosse — APPROVED** [review]
Very good, thanks!

**Pull request merged**
