### PR TITLE
Ref 005-Codelist extension / composition

### LINKED ISSUE #106: Show codelist inheritance
Once codelist inheritance has been added to the SDMX information model, we'll need to add support for it in the API.

It was proposed to add a new value to the detail parameter. The issue with this is that this new value would only be relevant in case the resource type is `codelist`. 

An alternative would be to create a new resource type for this instead (e.g. codelist_ext or similar). 

And there might be other options as well.

### PR DESCRIPTION
**Pull request by sosna**
This adds support for Ref 005, implementing the solution documented on the [issue list](https://github.com/sdmx-twg/sdmx-rest/issues/106)/

Close #106

### CODE REVIEW

**Review by dosse — COMMENTED** [review]
Could I suggest to review the wording? The option list becomes more confusing because the original long sentence is now split into several separate sentences. I would suggest the following wording:

_This attribute specifies the desired amount of information to be returned. For example, it is possible to instruct the web service to return only basic information about the maintainable artefact (i.e.: id, agency id, version and name). Most notably, items of item schemes will not be returned (for example, it will not return the codes in a code list query). Possible values are: (1) `allstubs`: all artefacts should be returned as stubs, containing only identification information, as well as the artefacts' name. (2) `referencestubs`: referenced artefacts should be returned as stubs, containing only identification information, as well as the artefacts' name. (3) `referencepartial`: referenced item schemes should only include items used by the artefact to be returned. For example, a concept scheme would only contain the concepts used in a DSD, and its `isPartial` flag would be set to `true`. Likewise, if a dataflow has been constrained, then the codelists referenced by the DSD referenced by the dataflow should only contain the codes allowed by the content constraint. (4) `allcompletestubs`: all artefacts should be returned as complete stubs, containing identification information, the artefacts' name, description, annotations and isFinal information. (5) `referencecompletestubs`: referenced artefacts should be returned as complete stubs, containing identification information, the artefacts' name, description, annotations and isFinal information. (6) `raw`: returned codelists should include the `ExtendedBy` property, thereby allowing clients to see the inherited codelists, if any. (7) `partialraw`: referenced item schemes should only include items used by the artefact to be returned, as for the value 'referencepartial'. In addition, returned codelists should include the `ExtendedBy` property, thereby allowing clients to see the inherited codelists, if any, but only those used by the artefact are to be returned. (8) `full`: all available information for all artefacts should be returned._

I'm not sure how the `full` option will behave now. Does it include the `ExtendedBy` property? I liked the original 005 feature description explaining the **resolution** of codelists for these options, e.g. "returns a **resolved** full version", which was very clear, but which is not included in the doc.

**Comment by sosna** [comment]
Thanks @dosse. I have included all your comments, I think. Would you mind checking again? Thanks!

**Comment by dosse** [comment]
Hi @sosna, that's much better, thanks. Could I please suggest an additional improvement (reordering, completion and parameter meaning "inheritance" to avoid duplication) to make things even more clearer?:

----------------
This attribute specifies the desired amount of information to be returned. For example, it is possible to instruct the web service to return only basic information about the maintainable artefact (i.e.: id, agency id, version and name). Most notably, items of item schemes will not be returned (for example, it will not return the codes in a code list query). Possible values are: 
(1) `full`: all available information for all returned artefacts should be returned. Returned extended codelists are to be resolved, i.e. include all inherited codes, and must not include the `ExtendedBy` property. Not directly referenced inherited codelists are not returned.
(2) `allstubs`: all returned artefacts should be returned as stubs, i.e. only containing identification information and the artefacts' name. 
(3) `referencestubs`: same as `full` with the exception that referenced artefacts should be returned only as stubs, i.e. only containing identification information and the artefacts' name.
(4) `allcompletestubs`: all returned artefacts should be returned as complete stubs, i.e. only containing identification information, the artefacts' name, description, annotations and isFinal information. 
(5) `referencecompletestubs`: same as `full` with the exception that referenced artefacts should be returned as complete stubs, i.e. only containing identification information, the artefacts' name, description, annotations and isFinal information. 
(6) `referencepartial`: same as `full` with the exception that referenced item schemes should only include items used by the artefact to be returned. For example, a concept scheme would only contain the concepts used in a DSD, and its isPartial flag would be set to true. Likewise, if a dataflow has been constrained, then the codelists referenced by the DSD referenced by the dataflow should only contain the codes allowed by the content constraint.
(7) `raw`: same as `full` with the exception that the returned extended codelists are not resolved and must include the `ExtendedBy` property, and if referenced codelists or descendants are to be returned then they include also all inherited codelists. 
(8) `partialraw`: same as `raw` with the exception that referenced item schemes, also including returned inherited codelists, should only include items used by the artefact to be returned, similar to the value 'referencepartial'.  

----------------

I have an additional question: The default `full` option, I guess, is used mainly for visualisations and the `ExtendedBy` property is not required for such a use. When copying artefacts from one registry to another, then we must use in the future always the `raw` option, in order to not loose any information, right? What, I think, is then currently dangerous is that users might use an extraction done with the default `full` option to copy artefacts into another registry/store, which means they store incorrect artefacts without knowing/realising the mistake. Shouldn't we have a special property (similar to `isPartial`) to indicate that the user is dealing with a resolved artefact rather than a raw artefact? `ExtendedBy` isn't of use here because not all codelists are extended. Do we need an additional `isExtended` property for resolved codelists?

**Comment by sosna** [comment]
Thanks, @dosse! I have included all your suggestions except the following part: "Not directly referenced inherited codelists are not returned", as I was not sure to understand what was meant. Did you mean the following: As inherited codelists have been resolved, they must not be returned as separated codelists?

Re. your question: Good point, it might make sense to add this additional attribute but this would be a question for TF2 I guess. @stratosn, what do you think?

**Comment by dosse** [comment]
@sosna What I meant was the following bold part of the description in https://github.com/sdmx-twg/sdmx-rest/issues/106:

- _/dataflow/SDMX/TEST/latest?references=all&detail=full: Returns a resolved full version of the CL_AREA codelist. That codelist includes all the CL_AREA local codes, as well as all the codes from CL_EUROPE and CL_ASIA. It does not contain any ExtendedBy information. **Although references=descendants, CL_EUROPE and CL_ASIA are not part of the response** because their codes have been merged in CL_AREA, thanks to the resolution mechanism. The other (simple) codelists referenced by the DSD are displayed in a similar fashion, i.e. with all their codes and no ExtendedBy information._ 

Without the proposed text "_Not directly referenced inherited codelists are not returned_", the codelists CL_EUROPE and CL_ASIA would have to be part of the response when _references=descendants&detail=full_.

**Comment by sosna** [comment]
Thanks, @dosse. I have added one sentence and hope it clarifies.

**Comment by dosse** [comment]
Great! Very last thing ;-) I promise : Shouldn't `v2_1/ws/rest/src/sdmx-rest.yaml` also be updated with the new option descriptions?

**Comment by sosna** [comment]
Thanks, @dosse. The YAML file has been updated accordingly :).

**Review by dosse — APPROVED** [review]
Great, thanks!

**Pull request merged**
