### PR TITLE
Group all structural metadata queries under a structure resource

### LINKED ISSUE #85: 023-Group all structural metadata queries under a structure resource
It is proposed to group all structural metadata queries under a `structure` resource to ease the understanding of the API. After this has been done, the API would offer only 4 main resources:

- `data`: to retrieve statistical data
- `metadata`: to retrieve reference metadata
- `schema`: to retrieve schemas that can be used to validate data
- `structure`: to retrieve structural metadata 

The new *structure* query would be as follow: 
`resource/type/agency/id/version` (and of course `resource/type/agency/id/version/item`, for *item scheme* queries), where:

- _resource_ would take a fixed value (i.e. `structure`)
- _type_ would be the artefact type, as defined by the SDMX IM (i.e. codelist, datastructure, dataflow, etc.)
- The rest (`agency/id/version`) would not change compared to the current version
- Each of the path parameters (i.e. all except _resource_ in the definition above) accept the `all` keyword (in addition, _version_ also accept `latest`)
 
So, for example, to get the latest version of the SDMX CL_FREQ codelist, one would do:
`https://entry-point/structure/codelist/SDMX/CL_FREQ/latest` (`latest` could be omitted as it is the default value if not supplied)
 
To get the latest version of all structures maintained by SDMX, use the following:
`https://entry-point/structure/all/SDMX/all/latest` or simply `https://entry-point/structure/all/SDMX`, as `all` and `latest` are the default values for the _id_ and _version_ path parameters respectively.

### PR DESCRIPTION
**Pull request by sosna**
Close #85. See example on [SwaggerHub](https://app.swaggerhub.com/apis/sdmx-rest/sdmx-rest/2.0.0-SNAPSHOT)

### CODE REVIEW

**Comment by Tzaphkiel** [comment]
Dear @sosna , there seems to be multiple versions of the yaml rest api specifications in this one merge request... how will we distinguish the latest from the v2.0.0 ? (ie.: the last commit included in this pull request is for me not to be included).

**Comment by stratosn** [comment]
Dear @sosna, first of all, I hope that you are OK with me doing the changes on the .yaml file. 
If not, please let me know what would be the best way to make/propose the bug fixes.
I would also like to ask something about the path parameters. I see (also in the open api specs) that path parameters are always required. How is this compliant with the SDMX RESTful API that we foresee omitting a path parameter, implying a default value (e.g. the version)?

**Comment by sosna** [comment]
@stratosn, yes, please, go ahead, that's very helpful :)

Re. the path parameters: In my opinion, this makes things more explicit without breaking backwards compatibility. The alternative would be to define all options (e.g. /codelist/, /codelist/agency, /codelist/agency/resource, etc.). Maybe we can discuss this during the next telco?

**Comment by stratosn** [comment]
OK, that's great. The changes are already there.

For the parameters, let's discuss during our telco.

**Pull request merged**
